version: "3.7"

services:
  postgres:
    build:
      context: ./docker/postgres
      dockerfile: ./Dockerfile
    container_name: laen_postgres
    ports:
      - 5433:5432
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: laen
      POSTGRES_USER: laen
      POSTGRES_PASSWORD: laen
      TZ: "Europe/Tallinn"
volumes:
  postgres_data:
